# Generated by Django 5.0 on 2024-04-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotsmodel',
            name='source',
            field=models.IntegerField(default=1, verbose_name='数据来源'),
            preserve_default=False,
        ),
    ]
